[build]
  # Build command for Next.js
  command = "npm run build"
  
  # Publish directory - Let Netlify plugin handle this automatically
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Netlify-specific Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle all routes for Next.js App Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 