[build]
  # Build command for Next.js
  command = "npm run build"
  
  # Publish directory - Let Netlify plugin handle this automatically
  publish = ".next"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Next.js specific environment variables
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Build optimization
  NODE_OPTIONS = "--max-old-space-size=4096"

# Netlify-specific Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Handle Next.js pages and static files
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200
  headers = {Cache-Control = "public, max-age=31536000, immutable"}

# Handle all other routes for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Edge functions configuration
[edge_functions]
  directory = "netlify/edge-functions" 